spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/hyadmin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:/com/github/phy19870227/hyadmin/dao/*/xml/*Mapper.xml
  type-aliases-package: com.github.phy19870227.hyadmin.module.po
  global-config:
    id-type: 3
    refresh-mapper: true
    logic-delete-value: Y
    logic-not-delete-value: N
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
